# Copyright 2024 openGemini Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is the configuration file for the ts-trace server.
#
# server host
host: 0.0.0.0
# server port
port: 18086
# server log configuration
log:
  # log type, support text|json
  type: text
  # log level, support debug,info,warn,error
  level: info
  # log output filename
  output: trace.log
# opengemini server configuration
opengemini:
  # opengemini http server address
  address:
    - host: 0.0.0.0
      port: 8086
  # opengemini server auth config
  auth:
    username: admin
    password: admin
  # where database to store trace data
  database: jaeger_storage
  # retention strategy for trace data
  retention_policy: trace
  # time setting for retention policy
  retention_duration: 3d
  # opengemini grpc server address
  grpc_write:
    address:
      - host: 0.0.0.0
        port: 8305
